Table and column names
pdevito3/craftsman pull request #6
Opened 2020-12-16 23:47 UTC by jheizer

Allow the defining of table and column names to be added as attributes to the generated code.

Note branch was made after #5 so it includes those changes as well.

2020-12-18 19:58 UTC, pdevito3 commented
Ha, great minds 🙂 I actually just finished adding the capability to add table names and schemas for the next release (check out the [v6.x branch](https://github.com/pdevito3/craftsman/tree/v0.6.x). If you want you can go ahead and try to merge it in, otherwise, I'll leave this and try to merge before the next release as there's definitely some overlap. 

Regardless, appreciate the contributions!! Let me know if you want to work on any more features so we can sync up on things.

2020-12-22 22:33 UTC, pdevito3 commented on Craftsman.Tests/FileTextTests/EntityFileTextTests.cs
> +            var expectedText = @$"namespace Domain.Entities
Is this an accident?

2020-12-22 22:34 UTC, pdevito3 commented on Craftsman.Tests/FileTextTests/EntityFileTextTests.cs
> +}}";
This also looks like an accident?

2020-12-22 22:34 UTC, pdevito3 commented on Craftsman/Builders/EntityBuilder.cs
>  {{
Also a typo?

2020-12-22 22:37 UTC, pdevito3 commented on Craftsman/Models/Entity.cs
> +        /// <summary>
Could you remove table name? I've already added that separately.

2020-12-22 22:37 UTC, pdevito3 commented on Craftsman/Builders/EntityBuilder.cs
> +    {tableName}public class {entity.Name}{inheritanceString}
Could you remove table name? I've already added that separately.

2020-12-22 22:38 UTC, pdevito3 commented on Craftsman/Builders/EntityBuilder.cs
> +            if (!string.IsNullOrEmpty(entityProperty.ColumnName))
+1

2020-12-22 22:39 UTC, pdevito3 commented on Craftsman/Models/EntityProperty.cs
> +
+1

2020-12-22 22:40 UTC, pdevito3 requested changes
Hey, looks like there might have been a couple of characters accidentally deleted. Otherwise, could you just removed the tablename feature as I already added that in.

2020-12-22 22:55 UTC, jheizer commented
Hmm, I'm confused.  It might be github not liking the embedded strings with {{.  I see as red just reading the source on here.  Ex: https://github.com/pdevito3/craftsman/blob/master/Craftsman/Builders/EntityBuilder.cs  I don't see that I have changes on the given lines.

2020-12-22 22:58 UTC, pdevito3 commented
Yeah, I just looked at the PR on git fork to merge it in and those weren't showing up. Was about to comment to let you know. 

Don't worry about this, I just conflict resolved merge into v0.6 to tweak the tests a smidge to work for some controller updates i made. You should get the credit for the commits, so let me know if there is an issue

2020-12-22 23:05 UTC, pdevito3 approved these changes
looks good! I'll be sure to merge these in so you get credit. could you just change the merge branch from `pdevito3:master` to `pdevito3:v0.6.x`?

2020-12-22 23:06 UTC, jheizer commented
Pushed changes in there, hopefully didn't mess things up.  It showing those characters in red sure is annoying

2020-12-22 23:10 UTC, merged